In [1]:
import numpy as np

In [37]:
# with numpy library
def compute_norms(x):
    norm_1 = np.linalg.norm(x,1)
    norm_2 = np.linalg.norm(x,2)
    norm_inf = np.max(np.abs(x))
    return norm_1, norm_2, norm_inf

x = np.array([1,-2,3,-4])
norms = compute_norms(x)
print(f'L1 norm = {norms[0]}\nL2 norm = {norms[1]}\nInfinite norm = {norms[2]}\n')

# only python 
def comp_norms(y):
    norm_1 = 0
    norm_2 = 0
    inf_norm = []
    for i in y:
        if i < 0:
            norm_1 = norm_1 + (i * (-1))
            norm_2 = norm_2 + i**2
            inf_norm.append(i*(-1))
        else:
            norm_1 = norm_1 + i
            norm_2 = norm_2 + i**2
            inf_norm.append(i)
            
    return norm_1, norm_2 ** (1/2), max(inf_norm)

x = np.array([1,-2,3,-4,])
norm = comp_norms(x)
print(norm)

L1 norm = 10.0
L2 norm = 5.477225575051661
Infinite norm = 4

(10, 5.477225575051661, 4)


In [45]:
def chek_treangle_rule(x, y):
    return np.linalg.norm(x+y, 2) <= np.linalg.norm(x,2) + np.linalg.norm(x,2)

x = np.array([1, -2, 3])
y = np.array([4, -1, 0])
print("Triangle inequality holds:", chek_treangle_rule(x, y))

Triangle inequality holds: True


In [69]:
# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix operations
print("Matrix A:\n", A)
print("Matrix B:\n", B)

print('Matrix A * B =\n', A @ B)

print(f'Transpose A:\n{A.T}')

print(f'Transpose A:\n{np.linalg.inv(A)}')

print(f'Det A:\n{np.linalg.det(A)}')

print(f'Rank A:\n{np.linalg.matrix_rank(A)}')


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix A * B =
 [[19 22]
 [43 50]]
Transpose A:
[[1 3]
 [2 4]]
Transpose A:
[[-2.   1. ]
 [ 1.5 -0.5]]
Det A:
-2.0000000000000004
Rank A:
2


In [90]:
def projection_vectors(a,b):
    projection = np.dot(a,b) / np.dot(a,a) * a
    return projection
a = np.array([1, 2])
b = np.array([3, 4])
print("Projection of b onto a:", projection_vectors(a, b))

Projection of b onto a: [2.2 4.4]


In [92]:
def chek_orthogonality(x,y):
    return np.isclose(np.dot(x,y),0)
x = np.array([1,2])
y = np.array([-2,1])
print(chek_orthogonality(x,y))

True
